spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://au77784bkjx6ipju.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/ivmbb77blxm3zgsm?serverTimezone=UTC&characterEncoding=UTF-8
    username: dy2lz2k4vwyjimud
    password: d2uywz7qrfqbmapx

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
      use-new-id-generator-mappings: false

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false